/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface UbdButton {}
}

declare global {


  interface HTMLUbdButtonElement extends Components.UbdButton, HTMLStencilElement {}
  var HTMLUbdButtonElement: {
    prototype: HTMLUbdButtonElement;
    new (): HTMLUbdButtonElement;
  };
  interface HTMLElementTagNameMap {
    'ubd-button': HTMLUbdButtonElement;
  }
}

declare namespace LocalJSX {
  interface UbdButton {}

  interface IntrinsicElements {
    'ubd-button': UbdButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'ubd-button': LocalJSX.UbdButton & JSXBase.HTMLAttributes<HTMLUbdButtonElement>;
    }
  }
}


